GET http://localhost:4004/odata/EMPLOYEE

###

DELETE http://localhost:4004/odata/EMPLOYEE(8)

###
POST http://localhost:4004/odata/EMPLOYEE
Content-Type: application/json

{
    "EMP_ID": 5,
    "EMP_NAME": "Vidhi",
    "PASSWORD": "v12345",
    "EMAIL":"vidhi@vsdtechno.com",
    "PHONE_NO": 8990583965,
    "EMP_COUNTRY": "Uganda",
    "EMP_STATUS": false,
    "TILE_VISIBLITY": []
}


###
POST http://localhost:4004/odata/loginEmployee
Content-Type: application/json

{
    "EMP_NAME":"Kurvesh",
    "PASSWORD":"k123456"
}

###
GET http://localhost:4004/odata/ADMIN

###

POST http://localhost:4004/odata/loginAdmin
Content-Type: application/json

{
    "ADMIN_NAME":"Pratik",
    "PASSWORD":"p12345"
}

###
POST http://localhost:4004/odata/ADMIN
Content-Type: application/json

{
    "ADMIN_ID":9,
    "ADMIN_NAME":"Nilay",
    "PASSWORD":"n12345"
}

###

POST http://localhost:4004/odata/TILE
Content-Type: application/json

{
    "TILE_ID":2,
    "TILE_NAME":"Manage Vendor",
    "TILE_DESC":"Vendor management by admin"
}

###

POST http://localhost:4004/odata/CHANGE_EMP_PWD
Content-Type: application/json

{
    "USER_NAME":"Priyanka",
    "CURRENT_PWD":"p123456",
    "NEW_PWD":"p12345"
}

###
POST http://localhost:4004/odata/CHANGE_ADMIN_PWD
Content-Type: application/json

{
    "ADMIN_NAME":"Pratik",
    "CURRENT_PWD":"p123456",
    "NEW_PWD":"p12345"
}

###

POST http://localhost:4004/odata/MassUpdateEmployee
Content-Type: application/json

{
    "EMPLOYEES":
    [
        {
            "EMP_ID":1,
            "EMP_STATUS":true,
            "TILE_VISIBLITY":[2]
        },
        {
            "EMP_ID":2,
            "EMP_STATUS":true,
            "TILE_VISIBLITY":[1]
        },
        {
            "EMP_ID":4,
            "EMP_STATUS":true,
            "TILE_VISIBLITY":[1]
        }
        
    ]   
}

